/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hazydesigns.capstone.worldWindGazeInput;

import gov.nasa.worldwind.Model;
import gov.nasa.worldwind.WorldWind;
import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.avlist.AVKey;
import gov.nasa.worldwind.awt.WorldWindowGLCanvas;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author mhazlewood
 */
public class WorldWindPanel extends JPanel
{
   private WorldWindow mWorldWindow;

   /**
    * Creates new form WorldWindPanel
    * @param canvasSize
    */
   public WorldWindPanel(Dimension canvasSize)
   {
      super(new BorderLayout());      
      
      mWorldWindow = createWorldWindow();
      ((Component)mWorldWindow).setPreferredSize(canvasSize);
      
      // Create the default model as described in the current worldwind properties.
      Model m = (Model) WorldWind.createConfigurationComponent(AVKey.MODEL_CLASS_NAME);
      mWorldWindow.setModel(m);
      
      add((Component)mWorldWindow, BorderLayout.CENTER);
   }
   
   private WorldWindow createWorldWindow()
   {
       return new WorldWindowGLCanvas();
   }
   
   public WorldWindow getWorldWindow()
   {
      return mWorldWindow;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
