package com.hazydesigns.capstone.worldWindGazeInput;

import com.hazydesigns.capstone.worldWindGazeInput.ui.GazeControlsLayer;
import com.hazydesigns.capstone.worldWindGazeInput.ui.GazeControlsSelectListener;
import gov.nasa.worldwind.Model;
import gov.nasa.worldwind.WorldWind;
import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.avlist.AVKey;
import gov.nasa.worldwind.awt.WorldWindowGLCanvas;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 * Container panel for the World Wind view.
 * 
 * @author Mark Hazlewood
 * 
 * @see JPanel
 * @see WorldWindow
 */
public class WorldWindPanel extends JPanel
{
   private final WorldWindow mWorldWindow;

   /**
    * Creates new form WorldWindPanel
    * @param canvasSize
    */
   public WorldWindPanel(Dimension canvasSize)
   {
      super(new BorderLayout());      
      
      mWorldWindow = createWorldWindow();
      ((Component)mWorldWindow).setPreferredSize(canvasSize);
      
      // Create the default model as described in the current worldwind properties.
      Model m = (Model) WorldWind.createConfigurationComponent(AVKey.MODEL_CLASS_NAME);
      mWorldWindow.setModel(m);
      
      GazeControlsLayer controlLayer = new GazeControlsLayer();
      GazeControlsSelectListener controlSelectListener = new GazeControlsSelectListener(mWorldWindow, controlLayer);
      mWorldWindow.addSelectListener(controlSelectListener);
      mWorldWindow.getModel().getLayers().add(controlLayer);
      
      add((Component)mWorldWindow, BorderLayout.CENTER);      
      setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
   }
   
   /**
    * 
    * @return 
    */
   private WorldWindow createWorldWindow()
   {
       return new WorldWindowGLCanvas();
   }
   
   /**
    * 
    * @return 
    */
   public WorldWindow getWorldWindow()
   {
      return mWorldWindow;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
