/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hazydesigns.capstone.worldWindGazeInput.ui;

/**
 *
 * @author mhazlewood
 */
public class ConfigTestDialog extends javax.swing.JDialog 
{
    /**
     * Creates new form ConfigTestDialog
     */
    public ConfigTestDialog(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
    }
    
    public void setVisible(boolean visible, boolean showEdgePan, boolean showCenterPan, boolean showZoomIn, boolean showZoomOut)
    {
       mShowCenterPanCheck.setSelected(showCenterPan);
       mShowEdgePanCheck.setSelected(showEdgePan);
       mShowZoomInCheck.setSelected(showZoomIn);
       mShowZoomOutCheck.setSelected(showZoomOut);
       
       super.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      jPanel1 = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      mShowZoomOutCheck = new javax.swing.JCheckBox();
      jLabel2 = new javax.swing.JLabel();
      mShowZoomInCheck = new javax.swing.JCheckBox();
      mUiZoomModeRad = new javax.swing.JRadioButton();
      mDwellZoomModeRad = new javax.swing.JRadioButton();
      mShowCenterPanCheck = new javax.swing.JCheckBox();
      jLabel3 = new javax.swing.JLabel();
      mUiPanModeRad = new javax.swing.JRadioButton();
      mDwellPanModeRad = new javax.swing.JRadioButton();
      mShowEdgePanCheck = new javax.swing.JCheckBox();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

      jButton1.setText("OK");
      jButton1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton1ActionPerformed(evt);
         }
      });
      jPanel1.add(jButton1);

      getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

      jPanel2.setLayout(new java.awt.GridBagLayout());

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel1.setText("Zoom Mode:");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.ipady = 15;
      jPanel2.add(jLabel1, gridBagConstraints);

      mShowZoomOutCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mShowZoomOutCheck.setSelected(true);
      mShowZoomOutCheck.setText("Zoom Out");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 0;
      jPanel2.add(mShowZoomOutCheck, gridBagConstraints);

      jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel2.setText("Show:");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.ipady = 15;
      jPanel2.add(jLabel2, gridBagConstraints);

      mShowZoomInCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mShowZoomInCheck.setSelected(true);
      mShowZoomInCheck.setText("Zoom In");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 0;
      jPanel2.add(mShowZoomInCheck, gridBagConstraints);

      mUiZoomModeRad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mUiZoomModeRad.setSelected(true);
      mUiZoomModeRad.setText("Gaze UI");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 2;
      jPanel2.add(mUiZoomModeRad, gridBagConstraints);

      mDwellZoomModeRad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mDwellZoomModeRad.setText("Gaze Dwell");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 2;
      jPanel2.add(mDwellZoomModeRad, gridBagConstraints);

      mShowCenterPanCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mShowCenterPanCheck.setSelected(true);
      mShowCenterPanCheck.setText("Center Pan");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 4;
      gridBagConstraints.gridy = 0;
      jPanel2.add(mShowCenterPanCheck, gridBagConstraints);

      jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel3.setText("Pan Mode:");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.ipady = 15;
      jPanel2.add(jLabel3, gridBagConstraints);

      mUiPanModeRad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mUiPanModeRad.setSelected(true);
      mUiPanModeRad.setText("Gaze UI");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      jPanel2.add(mUiPanModeRad, gridBagConstraints);

      mDwellPanModeRad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mDwellPanModeRad.setText("Gaze Dwell");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 1;
      jPanel2.add(mDwellPanModeRad, gridBagConstraints);

      mShowEdgePanCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      mShowEdgePanCheck.setText("Edge Pan");
      mShowEdgePanCheck.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            mShowEdgePanCheckActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 3;
      gridBagConstraints.gridy = 0;
      jPanel2.add(mShowEdgePanCheck, gridBagConstraints);

      getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

   private void mShowEdgePanCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mShowEdgePanCheckActionPerformed
   {//GEN-HEADEREND:event_mShowEdgePanCheckActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_mShowEdgePanCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigTestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigTestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigTestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigTestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                ConfigTestDialog dialog = new ConfigTestDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public boolean getShowZoomIn()
    {
        return mShowZoomInCheck.isSelected();
    }
    
    public boolean getShowZoomOut()
    {
        return mShowZoomOutCheck.isSelected();
    }
    
    public boolean getShowEdgePan()
    {
       return mShowEdgePanCheck.isSelected();
    }
    
    public boolean getShowCenterPan()
    {
        return mShowCenterPanCheck.isSelected();
    }
    
    public boolean getPanUiMode()
    {
        return mUiPanModeRad.isSelected();
    }
    
    public boolean getZoomUiMode()
    {
        return mUiZoomModeRad.isSelected();
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JRadioButton mDwellPanModeRad;
   private javax.swing.JRadioButton mDwellZoomModeRad;
   private javax.swing.JCheckBox mShowCenterPanCheck;
   private javax.swing.JCheckBox mShowEdgePanCheck;
   private javax.swing.JCheckBox mShowZoomInCheck;
   private javax.swing.JCheckBox mShowZoomOutCheck;
   private javax.swing.JRadioButton mUiPanModeRad;
   private javax.swing.JRadioButton mUiZoomModeRad;
   // End of variables declaration//GEN-END:variables
}
