/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hazydesigns.capstone.worldWindGazeInput.ui;

import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Mark
 */
public class NewParticipantDialog extends javax.swing.JDialog
{
   private String mRecordDirectory = "";
   private int mParticipantNumber = 0;
   private int mStartingTaskNumber = 0;
   

   /**
    * Creates new form NewParticipantDialog
    */
   public NewParticipantDialog(java.awt.Frame parent, boolean modal)
   {
      super(parent, modal);
      initComponents();
   }
   
   public void show(String startingRecordDirectory, int participantNumber, int taskNumber)
   {
      mRecordDirectory = startingRecordDirectory;
      
      mParticipantNumber = participantNumber;
      mPartNumSpinner.setValue(mParticipantNumber);
      
      mStartingTaskNumber = taskNumber;
      mStartTaskSpinner.setValue(mStartingTaskNumber);
      
      this.setVisible(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        mPathField = new javax.swing.JTextField();
        mSetPathButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mPartNumLbl = new javax.swing.JLabel();
        mPartNumSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        mStartTaskLbl = new javax.swing.JLabel();
        mStartTaskSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mPathField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mPathField.setText("C:\\Users\\Mark\\Desktop");
        mPathField.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(mPathField, gridBagConstraints);

        mSetPathButton.setText("Set Directory");
        mSetPathButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mSetPathButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(mSetPathButton, gridBagConstraints);

        mPartNumLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mPartNumLbl.setText("Participant Number    ");
        jPanel1.add(mPartNumLbl);

        mPartNumSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mPartNumSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        mPartNumSpinner.setMinimumSize(new java.awt.Dimension(50, 20));
        mPartNumSpinner.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(mPartNumSpinner);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jPanel1, gridBagConstraints);

        mStartTaskLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mStartTaskLbl.setText("Starting Task Number");
        jPanel2.add(mStartTaskLbl);

        mStartTaskSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mStartTaskSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        mStartTaskSpinner.setMinimumSize(new java.awt.Dimension(50, 20));
        mStartTaskSpinner.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel2.add(mStartTaskSpinner);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jPanel2, gridBagConstraints);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void mSetPathButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mSetPathButtonActionPerformed
   {//GEN-HEADEREND:event_mSetPathButtonActionPerformed
      JFileChooser fc = new JFileChooser(mRecordDirectory);
      fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      
      int returnVal = fc.showOpenDialog(this);
      if (returnVal == JFileChooser.APPROVE_OPTION)
      {
         try            
         {
            mRecordDirectory = fc.getSelectedFile().getCanonicalPath();
            mPathField.setText(mRecordDirectory);
         }
         catch (IOException e)
         {
            e.printStackTrace();
         }
      }
   }//GEN-LAST:event_mSetPathButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(NewParticipantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(NewParticipantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(NewParticipantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(NewParticipantDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the dialog */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            NewParticipantDialog dialog = new NewParticipantDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter()
            {
               @Override
               public void windowClosing(java.awt.event.WindowEvent e)
               {
                  System.exit(0);
               }
            });
            dialog.setVisible(true);
         }
      });
   }
   
   public String getRecordPath()
   {
      return mPathField.getText();
   }
   
   public int getParticipantNumber()
   {
      return Integer.parseInt(mPartNumSpinner.getValue().toString());
   }
   
   public int getStartingTaskNumber()
   {
       return Integer.parseInt(mStartTaskSpinner.getValue().toString());
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mPartNumLbl;
    private javax.swing.JSpinner mPartNumSpinner;
    private javax.swing.JTextField mPathField;
    private javax.swing.JButton mSetPathButton;
    private javax.swing.JLabel mStartTaskLbl;
    private javax.swing.JSpinner mStartTaskSpinner;
    // End of variables declaration//GEN-END:variables
}
